cloud:
    aws:
        credentials:
            accessKey: FAKEKEY
            secretKey: FAKEKEY
            instanceProfile: false
        region:
            auto: false
            static: us-west-2
    rds:
        sample:
            password: masterpassword
            username: master
            readReplicaSupport: true
            databaseName: sample


endpoints:
    enabled: true
    sensitive: false

spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop