cloud:
    aws:
        credentials:
            accessKey: FAKEKEY
            secretKey: FAKEKEY
            instanceProfile: false
        region:
            auto: false
            static: us-west-2
        rds:
            sample:
                username: master
                password: masterpassword
                databaseName: sample
                # Spring casts all of these properties to String so we can't have Yaml use a boolean value
                readReplicaSupport: "true"


endpoints:
    enabled: true
    sensitive: false

spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop